# Generated by Django 6.0.1 on 2026-01-19 13:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactStatusChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nazwa statusu kontaktu, np. 'nowy', 'w trakcie'", max_length=50, unique=True, verbose_name='Nazwa statusu')),
                ('description', models.TextField(blank=True, help_text='Opcjonalny opis statusu', null=True, verbose_name='Opis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
            ],
            options={
                'verbose_name': 'Status kontaktu',
                'verbose_name_plural': 'Statusy kontaktów',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Imię kontaktu', max_length=100, verbose_name='Imię')),
                ('last_name', models.CharField(help_text='Nazwisko kontaktu', max_length=100, verbose_name='Nazwisko')),
                ('phone_number', models.CharField(help_text='Format: +48123456789', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Numer telefonu musi być w formacie: '+999999999'. Dozwolone 9-15 cyfr.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Numer telefonu')),
                ('email', models.EmailField(help_text='Unikalny adres email kontaktu', max_length=254, unique=True, verbose_name='Adres email')),
                ('city', models.CharField(help_text='Miasto zamieszkania (używane do pobierania pogody)', max_length=100, verbose_name='Miasto')),
                ('date_added', models.DateTimeField(auto_now_add=True, help_text='Data i czas dodania kontaktu do systemu', verbose_name='Data dodania')),
                ('status', models.ForeignKey(help_text='Aktualny status kontaktu', on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='contacts.contactstatuschoices', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Kontakt',
                'verbose_name_plural': 'Kontakty',
                'ordering': ['-date_added'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='contacts_co_last_na_bb56ce_idx'), models.Index(fields=['-date_added'], name='contacts_co_date_ad_b2a680_idx')],
            },
        ),
    ]
